spring:
  redis:
    database: 0            # Redis数据库索引（默认为0）
    #   url: redis://user:password@example.com:6379  # 采用url进行配置
    host: 172.17.213.205     # Redis服务器地址
    port: 6379             # Redis服务器连接端口
    #    password: 123456      # Redis服务器连接密码（默认为空），如果没有配置密码就不要写这个属性了
    timeout: 10000ms         # 客户端连接超时时间，单位是毫秒 默认是2000，即2秒
    #   ssl: false             # 是否开启SSL
    lettuce:                # 连接池设置
      pool:
        max-active: 5000      # 连接池最大连接数（使用负值表示没有限制）, 默认 8
        max-wait: 10000ms       # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 100        # 连接池中的最大空闲连接 默认 8
        min-idle: 0        # 连接池中的最小空闲连接，默认 0